import {
  FaCode, FaStar, FaBrain, FaBookOpen,
  FaRaspberryPi,
  FaLaptopCode,
  FaBiohazard,
  FaBook,
  FaInfinity,
  FaProjectDiagram,
  FaBalanceScale,
  FaCogs
} from 'react-icons/fa';
import { PiBoxingGloveFill, PiLinuxLogoFill, PiCodeSimpleFill, PiGraphFill } from "react-icons/pi";
import type { JourneyStep, SpriteSheetData } from './journey';
import { GiClothes, GiLaptop, GiSolarSystem, GiCrystalBall, GiScrollQuill, GiLaurels, GiGoldBar, GiAnvil } from 'react-icons/gi';
import { TbBrandVscode, TbMathSymbols, TbTopologyStar3 } from "react-icons/tb";
import { SiLetsencrypt, SiCplusplus, SiReact, SiTypescript } from "react-icons/si";
import { MdOutlineSportsKabaddi } from "react-icons/md";

import me from '../animation/me-spritesheet.png';

const meAnimation: SpriteSheetData = {
  spriteSheet: me,
  frameCount: 4,
  frameWidth: 96,
  frameHeight: 96,
  fps: 5,
};

export const journeySteps: JourneyStep[] = [
  {
    title: "The First Choice",
    date: "2015",
    location: "The Scholomance of Priestlands",
    description: "The journey begins! You stand at a crossroads. Will you join the Humanities cultists, weaving words and histories, or the STEM disciples, who seek to unravel the world's mechanics? This choice will shape your destiny.",
    questType: "The Scholar's Path",
    difficulty: "Trivial",
    recommendedLevel: 14,
    recommendedSkills: ["Curiosity", "Creativity", "Tome Inscription"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 500, icon: <FaStar /> },
      { type: "Skill", name: "Path of the STEM Disciple", icon: <GiSolarSystem /> },
      { type: "Skill", name: "Lesser Python Spells", icon: <FaCode /> },
      { type: "Skill", name: "Melee Training", icon: <PiBoxingGloveFill /> }
    ],
    specialItem: "GCSE Scroll",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
  },
  {
    title: "Strings of Lightning",
    date: "2015",
    location: "The Port City of Southampton",
    description: "Not all magic comes from books and tomes. You pick up the electric guitar, channeling energy through strings of steel. Chords roar like thunder, solos crackle like lightning. A different discipline—music—joins your arsenal of skills.",
    questType: "Paths of Discovery",
    difficulty: "Normal",
    recommendedLevel: 16,
    recommendedSkills: ["Rhythm", "Creativity", "Persistence"],
    progress: 80,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1200, icon: <FaStar /> },
      { type: "Skill", name: "Electric Guitar Riffs", icon: <FaBrain /> },
      { type: "Item", name: "Amplifier of Power", icon: <FaCogs /> },
    ],
    specialItem: "Guitar of Thunder",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "Courts of Hardwood",
    date: "2016",
    location: "The Scholomance of Priestlands",
    description: "Between books and spells, you take to the court. Here, a smaller band of five face off, the rhythm of dribbling and the swish of nets forming their own kind of incantation. Victory depends not just on strength, but agility and teamwork.",
    questType: "The Way of the Warrior",
    difficulty: "Easy",
    recommendedLevel: 15,
    recommendedSkills: ["Agility Buff", "Quick Reflexes", "Team Spirit"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 600, icon: <FaStar /> },
      { type: "Item", name: "Basketball Medal", icon: <GiLaurels /> },
      { type: "Skill", name: "Court Vision", icon: <FaBrain /> },
    ],
    specialItem: "GCSE Basketball Trophy",
    specialItemFrames: meAnimation,
    specialItemRarity: "Uncommon",
  },
  {
    title: "Whispers of Open Source",
    date: "2017",
    location: "The Green Shires of Hampshire",
    description: "An unexpected encounter with a group called the Linuxites opens a new path. They reject the gilded cages of the Window Imperialists and MacOS Empire, speaking of freedom and control under a warlock named Linus. They promise to show you a better way.",
    questType: "The Arcane Arts",
    difficulty: "Easy",
    recommendedLevel: 15,
    recommendedSkills: ["CLI Curses", "Freedom Fighter Ideals", "Tome of Py"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 190, icon: <FaStar /> },
      { type: "Item", name: "Mastery of the Terminal", icon: <FaBookOpen /> },
      { type: "Item", name: "Arcane Pi Spells", icon: <FaRaspberryPi /> },
      { type: "Skill", name: "Linux Loyalist", icon: <PiLinuxLogoFill /> },
    ],
    specialItem: "Raspberry Pi",
    specialItemFrames: meAnimation,
    specialItemRarity: "Uncommon",
  },
  {
    title: "The Serpent in the Stacks",
    date: "2019",
    location: "The Port City of Southampton",
    description: "Deep within the library, the Linuxites speak of a serpent that guards ancient knowledge—a creature of pure logic that can weave incantations to manipulate reality. You must seek its wisdom to unlock new powers.",
    questType: "The Arcane Arts",
    difficulty: "Easy",
    recommendedLevel: 16,
    recommendedSkills: ["Common Incantation Table", "Member of Wizards Guild", "Linux Loyalty"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 380, icon: <FaStar /> },
      { type: "Skill", name: "Interpreter Spells", icon: <FaBrain /> },
      { type: "Skill", name: "Greater Python Mastery", icon: <FaLaptopCode /> },
    ],
    specialItem: "Tome of Py",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
  },
  {
    title: "The Assassin's Shadow",
    date: "2019",
    location: "The Forest College of Brockenhurst",
    description: "You learn of a dark underworld that creates spells to break other spells. They call themselves Dark Wizards. To defend against them, you must understand their ways, walking the line between the White and Dark arts without losing yourself.",
    questType: "The Arcane Arts",
    difficulty: "Hard",
    recommendedLevel: 16,
    recommendedSkills: ["Incantation Mastery", "Tome of Py", "Terminal Mastery", "Web Dimension Knowledge"],
    progress: 29,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "Cloak of Anonymity", icon: <GiClothes /> },
      { type: "Skill", name: "Vulnerability Divination", icon: <GiCrystalBall /> },
    ],
    specialItem: "RSA Dagger",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "The Summons of the Society",
    date: "2020",
    location: "The Forest College of Brockenhurst",
    description: "The GCSE Scroll has unlocked new abilities. During celebrations, an ominous presence looms. 'Young scholar,' a voice intones, 'We are members of the Mathematics Society. We have been watching you. Join us outside.'",
    questType: "The Scholar's Path",
    difficulty: "Hard",
    recommendedLevel: 16,
    recommendedSkills: ["Strong STEM Curses", "Lesser Incantation Mastery", "Greater Tome Inscription"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1700, icon: <FaStar /> },
      { type: "Item", name: "Improved Fashion Sense", icon: <GiClothes /> },
      { type: "Skill", name: "HP Incantation Table", icon: <GiLaptop /> },
      { type: "Skill", name: "Incantation Buff", icon: <FaCode /> },
      { type: "Skill", name: "Lesser Biology Spells", icon: <FaBiohazard /> },
    ],
    specialItem: "Advanced Spell Tome",
    specialItemFrames: meAnimation,
    specialItemRarity: "Uncommon",
  },
  {
    title: "A Pact with the Imperialists",
    date: "2020",
    location: "The Forest College of Brockenhurst",
    description: "A wizard in the Society speaks of translating an ancient text into 'C#'. To understand this strange dialect, you must secretly meet the Windows Imperialists. The Linuxites must not discover this heresy.",
    questType: "The Arcane Arts",
    difficulty: "Normal",
    recommendedLevel: 17,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Diplomacy"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "Visual Studio Spell Buffs", icon: <TbBrandVscode /> },
      { type: "Skill", name: "Lesser Tome of C#", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "The Champion's Bout",
    date: "2020",
    location: "The Arenas of London",
    description: "Lost in tomes and incantations, you realize your melee skills have dulled. You return to the art of hand-to-hand combat, rising through the leagues until you find yourself at the national championship. It is time to test your body as well as your mind.",
    questType: "The Way of the Warrior",
    difficulty: "Heroic",
    recommendedLevel: 18,
    recommendedSkills: ["High Stamina", "Strength Buff", "Combat Intelligence"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "Fighter's Medallion", icon: <GiLaurels /> },
      { type: "Skill", name: "Combat Focus", icon: <FaBrain /> },
    ],
    specialItem: "Respect Buff",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "A Pilgrimage to the North",
    date: "2022",
    location: "The Northern Citadel of Heriot-Watt",
    description: "With the Advanced Spell Tome in hand, you journey north. Rumours say a powerful branch of the Mathematics Society lies in refuge there. You set out, anxious but determined to deepen your understanding of the world's fundamental laws.",
    questType: "The Scholar's Path",
    difficulty: "Normal",
    recommendedLevel: 18,
    recommendedSkills: ["Advanced Spell Casting", "Meet Mathematicians", "Greater Tome Inscription"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1200, icon: <FaStar /> },
      { type: "Item", name: "Secrets Spell Casting", icon: <SiLetsencrypt /> },
      { type: "Skill", name: "Advanced Maths Casting", icon: <FaBook /> },
      { type: "Skill", "name": "Advanced Athletic Abilities", icon: <MdOutlineSportsKabaddi /> },
      { type: "Skill", name: "Befriended Grand Wizard", icon: <FaBook /> },
    ],
    specialItem: "The Mathematician's Manifesto",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "The Forge of the JVM",
    date: "2022",
    location: "The Northern Citadel of Heriot-Watt",
    description: "Whispers spread of an enchanted forge known as the Java Virtual Machine. Unlike Python's fluid incantations, this magic is structured, strict, and resilient. To wield it is to command a language that powers vast kingdoms of code.",
    questType: "The Arcane Arts",
    difficulty: "Normal",
    recommendedLevel: 20,
    recommendedSkills: ["OOP Spellbook", "Incantation Discipline", "Patience"],
    progress: 70,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1800, icon: <FaStar /> },
      { type: "Skill", name: "Java Mastery", icon: <FaBookOpen /> },
      { type: "Skill", name: "Strong Type Binding", icon: <FaCogs /> },
    ],
    specialItem: "Tome of the JVM",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "The Uncrowned King",
    date: "2022",
    location: "The Arenas of London",
    description: "You return to the championship—stronger, faster, smarter. You fight with the precision of a mathematician and the spirit of a warrior. Though victory is claimed by another, your skill earns you a legendary status among your peers.",
    questType: "The Way of the Warrior",
    difficulty: "Deadly",
    recommendedLevel: 19,
    recommendedSkills: ["High Stamina", "Strength Buff", "BCCMA Respect", "Veteran's Experience"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 5000, icon: <FaStar /> },
      { type: "Item", name: "Championship Gloves", icon: <PiBoxingGloveFill /> },
      { type: "Skill", name: "Unbreakable Will", icon: <FaBrain /> },
    ],
    specialItem: "Silver Medal of the Uncrowned",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "A Fool's Gamble",
    date: "2022",
    location: "The Londoninium Sprawl",
    description: "Drawn by tales of quick riches, you enter the chaotic realm of financial trading. It's a dangerous game of predicting the unpredictable, where fortunes are won and lost in moments. You try to read the market's cryptic signs, hoping not to lose your shirt.",
    questType: "The Gold-Spinner's Gambit",
    difficulty: "Normal",
    recommendedLevel: 19,
    recommendedSkills: ["Risk Assessment", "Emotional Detachment", "Basic Economics"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 800, icon: <FaStar /> },
      { type: "Item", name: "Slightly Emptier Coin Purse", icon: <GiGoldBar /> },
      { type: "Skill", name: "Humility", icon: <FaBrain /> },
    ],
    specialItem: "A Valuable Lesson",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
  },
  {
    title: "The Clash of the Fifteen",
    date: "2022",
    location: "The Grand Athenaeum of Queen Mary",
    description: "Your mind sharpens in lecture halls, but the pitch calls you to battle. You take up the sport of Rugby, where fifteen warriors clash in contests of speed, strength, and strategy. Each match is a proving ground for resilience and camaraderie.",
    questType: "The Way of the Warrior",
    difficulty: "Heroic",
    recommendedLevel: 18,
    recommendedSkills: ["Strength Buff", "Team Coordination", "Fearless Spirit"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 2200, icon: <FaStar /> },
      { type: "Item", name: "University Jersey", icon: <GiLaurels /> },
      { type: "Skill", name: "Tactical Awareness", icon: <FaBrain /> },
    ],
    specialItem: "Rugby Ball of Unity",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
    {
    title: "The Proving Grounds of London",
    date: "2023",
    location: "The Grand Athenaeum of Queen Mary",
    description: "Your studies in the north are complete, but whispers from the south tell of even more advanced Mathematical spells. You return to London, seeking to transcend from apprentice to master. The journey will be perilous, but the rewards are legendary.",
    questType: "The Scholar's Path",
    difficulty: "Heroic",
    recommendedLevel: 20,
    recommendedSkills: ["Advanced Spell Casting", "Russell Group Entry", "Greater Tome Inscription"],
    progress: 67,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 4000, icon: <FaStar /> },
      { type: "Item", name: "Pure Math Spells", icon: <FaBook /> },
      { type: "Item", name: "Statistical Magic", icon: <FaBook /> },
      { type: "Item", name: "R Inscription", icon: <PiCodeSimpleFill /> },
    ],
    specialItem: "Degree of Mathematical Wizardry",
    specialItemFrames: meAnimation,
    specialItemRarity: "Legendary",
  },
  {
    title: "The Bounty Hunter's Path",
    date: "2023",
    location: "The Eastern Marches of Ilford",
    description: "Your knowledge of the White Wizards' defensive arts has spread. Guilds and merchants now seek you out, asking you to test their web dimensions and break their spells—for a handsome price. If you succeed, gold and renown await.",
    questType: "The Arcane Arts",
    difficulty: "Heroic",
    recommendedLevel: 20,
    recommendedSkills: ["White Wizard Membership", "Exceptional Inscription Spells", "Network Reconnaissance"],
    progress: 12,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 10000, icon: <FaStar /> },
      { type: "Item", name: "Pen-Tester's Toolkit", icon: <FaCogs /> },
      { type: "Skill", name: "Ethical Spellbreaking", icon: <FaBalanceScale /> },
    ],
    specialItem: "Bounty Hunter's Hat",
    specialItemFrames: meAnimation,
    specialItemRarity: "Legendary",
  },
  {
    title: "The Trial of Infinite Sums",
    date: "2023",
    location: "The Grand Athenaeum of Queen Mary",
    description: "The Mathematics Society presents its first true test: Real Analysis. They speak of limits, continuity, and infinite series. To master these spells is to understand the very fabric of the number line. Many apprentices are driven mad by the epsilon-delta proofs.",
    questType: "The Scholar's Path",
    difficulty: "Hard",
    recommendedLevel: 20,
    recommendedSkills: ["Advanced Spell Tome", "Mathematical Maturity", "Persistence"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 2500, icon: <FaStar /> },
      { type: "Skill", name: "Proof by Contradiction", icon: <FaBrain /> },
      { type: "Skill", name: "Understanding of Infinity", icon: <FaInfinity /> },
    ],
    specialItem: "Convergence Charm",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "Weaving the Web",
    date: "2024",
    location: "The Alchemist's Union, Mile End",
    description: "An opportunity arises at the University to work with Earthly Networks. This 'Web' development is a different kind of magic, tangible and visual. Hungry for knowledge, you dive in, seeking to bend the Web dimension to your will.",
    questType: "The Arcane Arts",
    difficulty: "Easy",
    recommendedLevel: 20,
    recommendedSkills: ["Good Incantation Mastery", "HTML Scroll", "CSS Scroll", "JavaScript Scroll"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 200, icon: <FaStar /> },
      { type: "Item", name: "Web Weaver Tools", icon: <FaLaptopCode /> },
      { type: "Skill", name: "DOM Manipulation", icon: <FaBrain /> },
    ],
    specialItem: "Handbook to Web Dimensions",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
  },
  {
    title: "Scribing for Scraps",
    date: "2024",
    location: "The Londoninium Sprawl",
    description: "Funds run low during your studies. You turn to the Web dimension and find an odd job: producing simple incantations for gold. You're told it contributes to a grand, mysterious project. For now, it keeps your coin purse from being empty.",
    questType: "The Gold-Spinner's Gambit",
    difficulty: "Trivial",
    recommendedLevel: 20,
    recommendedSkills: ["Incantation Table", "Access to Web", "Basic Literacy"],
    progress: 80,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1500, icon: <FaStar /> },
      { type: "Item", name: "Heavier Coin Purse", icon: <GiGoldBar /> },
      { type: "Skill", name: "Data Annotation", icon: <FaCode /> },
    ],
    specialItem: "A Healthy Sum of Gold",
    specialItemFrames: meAnimation,
    specialItemRarity: "Uncommon",
  },
  {
    title: "The Alchemist's Golem",
    date: "2024",
    location: "The Londoninium Sprawl",
    description: "Manual trading is for commoners. You merge your Python spells with your market knowledge, crafting an algorithmic golem to trade for you. It can execute strategies faster than any mortal, but can you inscribe the right commands to tame the market beast?",
    questType: "The Gold-Spinner's Gambit",
    difficulty: "Hard",
    recommendedLevel: 21,
    recommendedSkills: ["Tome of Py", "API Integration", "Statistical Magic"],
    progress: 60,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 5000, icon: <FaStar /> },
      { type: "Item", name: "Automated Trading Script", icon: <FaCode /> },
      { type: "Skill", name: "Quantitative Analysis", icon: <PiGraphFill /> },
    ],
    specialItem: "The Black Box",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "Charting the Imaginary Plane",
    date: "2024",
    location: "The Grand Athenaeum of Queen Mary",
    description: "You venture into a new dimension of numbers: the complex plane. Here, incantations behave in strange and beautiful ways, solving problems once thought impossible in the real realm. You must learn the power of residues and contour integrals.",
    questType: "The Scholar's Path",
    difficulty: "Hard",
    recommendedLevel: 21,
    recommendedSkills: ["Convergence Charm", "Geometric Intuition", "Visualisation"],
    progress: 90,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 3000, icon: <FaStar /> },
      { type: "Skill", name: "Cauchy's Integral Formula", icon: <TbMathSymbols /> },
      { type: "Item", name: "Argand Diagram Map", icon: <PiGraphFill /> },
    ],
    specialItem: "Residue Theorem Scroll",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "Secrets of the Integers",
    date: "2024",
    location: "The Grand Athenaeum of Queen Mary",
    description: "This ancient branch of mathematics deals with prime numbers, the building blocks of reality. The spells are simple to state but fiendishly difficult to prove. You must seek patterns in the chaos, following the whispers of Fermat's Last Theorem.",
    questType: "The Scholar's Path",
    difficulty: "Normal",
    recommendedLevel: 21,
    recommendedSkills: ["Logic", "Abstract Reasoning", "Tome of Py"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 2000, icon: <FaStar /> },
      { type: "Skill", name: "Modular Arithmetic", icon: <FaCode /> },
      { type: "Skill", name: "Diophantine Equations", icon: <FaBookOpen /> },
    ],
    specialItem: "Prime Sieve of Eratosthenes",
    specialItemFrames: meAnimation,
    specialItemRarity: "Uncommon",
  },
  {
    title: "The Arch-Linux Heresy",
    date: "2025",
    location: "The Hermitage at Gants Hill",
    description: "The Linuxites emerge from the digital ether after a long absence. 'It's time you convert,' they hiss on a harsh winter night. 'To what?' you ask. 'To Arch.' You begin the long, arduous journey of taming the purest, most unforgiving form of their magic.",
    questType: "The Arcane Arts",
    difficulty: "Hard",
    recommendedLevel: 21,
    recommendedSkills: ["Terminal Lexicon", "Patience", "Devout Linuxite", "System Architecture"],
    progress: 32,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 3500, icon: <FaStar /> },
      { type: "Item", name: "Dotfile Grimoire", icon: <GiScrollQuill /> },
      { type: "Skill", name: "Absolute System Control", icon: <FaProjectDiagram /> },
    ],
    specialItem: "Arch Inscription Table",
    specialItemFrames: meAnimation,
    specialItemRarity: "Legendary",
  },
  {
    title: "The Thinkpad Guild",
    date: "2025",
    location: "The Green Shires of Hampshire",
    description: "You stumble upon the Thinkpad Guild, an offshoot of the Linuxites who craft their own custom inscription tables. They are secretive, but their hardware enchantments are legendary. Joining them could allow you to forge your own legendary tool.",
    questType: "The Arcane Arts",
    difficulty: "Normal",
    recommendedLevel: 21,
    recommendedSkills: ["Incantation Mastery", "Tinkerer's Delicacy", "Soldering Iron", "Haggling"],
    progress: 41,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "Custom Keycaps", icon: <GiAnvil /> },
      { type: "Skill", name: "Hardware Enchantment", icon: <GiLaptop /> },
    ],
    specialItem: "T480 Inscription Table",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "The Unforgiving Languages",
    date: "2025",
    location: "The Grand Athenaeum of Queen Mary",
    description: "The Society requires you to wield more direct power. You must learn the ancient and unforgiving languages of C and C++. These spells offer no safety nets; a single mistake can cause a cataclysmic 'segmentation fault'. But their control over the machine is absolute.",
    questType: "The Scholar's Path",
    difficulty: "Heroic",
    recommendedLevel: 21,
    recommendedSkills: ["OOP Spellbook", "Pointer Proficiency", "Memory Management"],
    progress: 50,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 4000, icon: <FaStar /> },
      { type: "Skill", name: "Greater Tome of C++", icon: <SiCplusplus /> },
      { type: "Skill", name: "Numerical Methods", icon: <TbMathSymbols /> },
    ],
    specialItem: "Pointer to Pointer",
    specialItemFrames: meAnimation,
    specialItemRarity: "Legendary",
  },
  {
    title: "Shaping the Unseen",
    date: "2025",
    location: "The Grand Athenaeum of Queen Mary",
    description: "You've mastered numbers, but what about shape? Topology is the study of properties that survive stretching and bending. In this realm, a coffee cup and a doughnut are one and the same. This abstract magic challenges your very perception of space.",
    questType: "The Scholar's Path",
    difficulty: "Heroic",
    recommendedLevel: 21,
    recommendedSkills: ["Abstract Reasoning", "Visualisation", "Set Theory"],
    progress: 80,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 3500, icon: <FaStar /> },
      { type: "Skill", name: "Homeomorphism", icon: <TbTopologyStar3 /> },
      { type: "Item", name: "Lens of Abstraction", icon: <GiCrystalBall /> },
    ],
    specialItem: "The Möbius Strip",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "The Language of Symmetry",
    date: "2025",
    location: "The Grand Athenaeum of Queen Mary",
    description: "The final trial in pure mathematics: Group Theory. This is the study of symmetry, the hidden structure governing everything from crystals to physics. The spells are abstract, dealing with objects you've never encountered. Can you grasp the fundamental language of the universe?",
    questType: "The Scholar's Path",
    difficulty: "Deadly",
    recommendedLevel: 21,
    recommendedSkills: ["Abstract Reasoning", "Proof Writing", "All Previous Maths Skills"],
    progress: 75,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 6000, icon: <FaStar /> },
      { type: "Skill", name: "Understanding of Symmetry", icon: <FaInfinity /> },
      { type: "Skill", name: "Isomorphism Recognition", icon: <FaProjectDiagram /> },
    ],
    specialItem: "Cayley's Amulet",
    specialItemFrames: meAnimation,
    specialItemRarity: "Legendary",
  },
  {
    title: "The Chronicler's Task",
    date: "2025",
    location: "The Londoninium Sprawl",
    description: "To chronicle your journey, you must build your own corner of the Web Dimension. This requires powerful modern frameworks like React and the strict, arcane syntax of TypeScript. A quest that tests both logic and artistry, this is the meta-narrative of your adventure.",
    questType: "The Chronicler's Task",
    difficulty: "Normal",
    recommendedLevel: 21,
    recommendedSkills: ["Handbook to Web Dimensions", "Design Principles", "Component-Based Architecture"],
    progress: 95,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 2500, icon: <FaStar /> },
      { type: "Skill", name: "React Sorcery", icon: <SiReact /> },
      { type: "Skill", name: "TypeScript Runes", icon: <SiTypescript /> },
    ],
    specialItem: "Portfolio of Power",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "The Highlands Call",
    date: "2025",
    location: "The Whispering Peaks of the Cairngorms",
    description: "The ancient mountains whisper with the voice of the wind. You hike through rugged highlands, facing cold rains, vast valleys, and breathtaking peaks. Here, magic is not written in code or books—it is carved into stone and sky.",
    questType: "Paths of Discovery",
    difficulty: "Hard",
    recommendedLevel: 21,
    recommendedSkills: ["Endurance", "Navigation", "Love of Nature"],
    progress: 90,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 3000, icon: <FaStar /> },
      { type: "Item", name: "Highland Compass", icon: <GiCrystalBall /> },
      { type: "Skill", name: "Survivor's Resilience", icon: <FaBalanceScale /> },
    ],
    specialItem: "Stone of the Cairngorms",
    specialItemFrames: meAnimation,
    specialItemRarity: "Legendary",
  },
];