import {
  FaCode, FaStar, FaBrain, FaBookOpen,
  FaRaspberryPi,
  FaLaptopCode,
  FaBiohazard,
  FaBook
} from 'react-icons/fa';
import { PiBoxingGloveFill, PiLinuxLogoFill } from "react-icons/pi";
import type { JourneyStep, SpriteSheetData } from './journey';
import { GiClothes, GiLaptop, GiSolarSystem } from 'react-icons/gi';

import me from '../animation/me-spritesheet.png'; 

const meAnimation: SpriteSheetData = {
  spriteSheet: me,
  frameCount: 4,
  frameWidth: 96,
  frameHeight: 96,
  fps: 5,
};

export const journeySteps: JourneyStep[] = [
  {
    title: "Tutorial",
    date: "2015",
    location: "Priestlands School",
    description: "The journey begins! Choose your faction whether that's the Humanities cultist or STEM disciples. This will begin to shape your character build. Certain spells are unlocked depending on the faction you choose.",
    questType: "Main Story",
    difficulty: "Trivial",
    recommendedLevel: 14,
    recommendedSkills: ["Curiosity", "Creativity", "Tome Inscription"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 500, icon: <FaStar /> },
      { type: "Skill", name: "STEM Disciple", icon: <GiSolarSystem /> },
      { type: "Skill", name: "Python Spells", icon: <FaCode /> },
      { type: "Skill", name: "PE Buff", icon: <PiBoxingGloveFill /> }
    ],
    specialItem: "GCSE Scroll",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
  },
  {
    title: "A visit from the Linuxites",
    date: "2017",
    location: "Hampshire",
    description: "An unexpected encounter with a group called the Linuxites opens a new path. It's not easy, many spells are closed to you, but they claim they can show you a new and better way. They say their leader is a Warlock called Linus. He has mastery over the Open Source domain. Maybe I can learn from him...",
    questType: "Linux Story Line",
    difficulty: "Easy",
    recommendedLevel: 15,
    recommendedSkills: ["CLI curses", "Freedom Fighter", "Oppose Window Imperialist", "Oppose MacOS Empire"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 2500, icon: <FaStar /> },
      { type: "Item", name: "Mastery of Terminal Buffs", icon: <FaBookOpen /> },
      { type: "Item", name: "Arcane Pi Spells", icon: <FaRaspberryPi /> },
      { type: "Skill", name: "Linux Loyalist", icon: <PiLinuxLogoFill /> },
    ],
    specialItem: "Raspberry Pi",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "The Library Serpent",
    date: "2019",
    location: "Southampton",
    description: "You find yourself in the depths of the library after meeting several Linux Loyalists. They speak of a serpent that guards ancient knowledge. This serpent can create incantations that manipulate the fabric of reality. You must seek its wisdom to unlock new powers.",
    questType: "Coding Story Line",
    difficulty: "Easy",
    recommendedLevel: 12,
    recommendedSkills: ["Common Incantation Table", "Member of Wizards Guild", "Earthly Network Caster"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Skill", name: "Interpreter Spells", icon: <FaBrain /> },
      { type: "Skill", name: "Lesser Incantation Mastery", icon: <FaLaptopCode /> },
    ],
    specialItem: "Tome of Py",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
  },
  {
    title: "Advanced Society",
    date: "2020",
    location: "Brockenhurst",
    description: "You have obtained the GCSE Scroll which has unlocked new spells and abilities. During celebrations with your fellow STEM disciples an ominous presence looms. 'Hello, young scholar. Meet me and my party outside - we are members of the Mathematics Society'. You finish your drink and step outside...",
    questType: "Main Story",
    difficulty: "Hard",
    recommendedLevel: 16,
    recommendedSkills: ["Strong STEM Curses", "Lesser Incantation Mastery", "Greater Tome Inscription"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 15000, icon: <FaStar /> },
      { type: "Item", name: "Improved Fashion Sense", icon: <GiClothes /> },
      { type: "Skill", name: "HP Incantation Table", icon: <GiLaptop /> },
      { type: "Skill", name: "Incantation Buff", icon: <FaCode /> },
      { type: "Skill", name: "Lesser Biology Spells", icon: <FaBiohazard /> },
    ],
    specialItem: "Advanced Spell Tome",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "Ancient Scriptures Recovered",
    date: "2020",
    location: "Brockenhurst",
    description: "You converse with a Wizard within the Mathematics Society casually. They mention an ancient scroll that they have been working on. The wizard claims that they've translated it into 'C#'. You enquire more. To understand the Wizards translation you secretly meet up with Windows Imperialists - the Linuxites best not see this...",
    questType: "Coding Story Line",
    difficulty: "Normal",
    recommendedLevel: 15,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Incantation Table"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "VS Spell Buffs", icon: <GiClothes /> },
      { type: "Skill", name: "Lesser Tome of C", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "Travels to the North",
    date: "2022",
    location: "Edinburgh",
    description: "After obtaining the Advanced Spell Tome during your time in whimsical Brockenhurst, you set out on a journey to the North. There were rumours that the Mathematical Society lay refuge there. You set out, anxious but determined.",
    questType: "Main Story",
    difficulty: "Hard",
    recommendedLevel: 18,
    recommendedSkills: ["Advanced Spell Casting", "Acquainted With Math Members", "Greater Tome Inscription"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 5000, icon: <FaStar /> },
      { type: "Item", name: "Secrets Spell Casting", icon: <GiClothes /> },
      { type: "Skill", name: "Advanced Maths Casting", icon: <FaBook /> },
      { type: "Skill", name: "Advanced Athletic Abilities", icon: <FaBook /> },
    ],
    specialItem: "The Mathematicians Manifesto",
    specialItemFrames: meAnimation,
    specialItemRarity: "Epic",
  },
  {
    title: "A New Dawn",
    date: "2020",
    location: "Brockenhurst",
    description: "You converse with a Wizard within the Mathematics Society casually. They mention an ancient scroll that they have been working on. The wizard claims that they've translated it into 'C#'. You enquire more. To understand the Wizards translation you secretly meet up with Windows Imperialists - the Linuxites best not see this...",
    questType: "Coding Story Line",
    difficulty: "Normal",
    recommendedLevel: 15,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Incantation Table"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "VS Spell Buffs", icon: <GiClothes /> },
      { type: "Skill", name: "Lesser Tome of C", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "The Linuxites Return",
    date: "2020",
    location: "Brockenhurst",
    description: "You converse with a Wizard within the Mathematics Society casually. They mention an ancient scroll that they have been working on. The wizard claims that they've translated it into 'C#'. You enquire more. To understand the Wizards translation you secretly meet up with Windows Imperialists - the Linuxites best not see this...",
    questType: "Coding Story Line",
    difficulty: "Normal",
    recommendedLevel: 15,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Incantation Table"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "VS Spell Buffs", icon: <GiClothes /> },
      { type: "Skill", name: "Lesser Tome of C", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "Spell Assassin",
    date: "2020",
    location: "Brockenhurst",
    description: "You converse with a Wizard within the Mathematics Society casually. They mention an ancient scroll that they have been working on. The wizard claims that they've translated it into 'C#'. You enquire more. To understand the Wizards translation you secretly meet up with Windows Imperialists - the Linuxites best not see this...",
    questType: "Coding Story Line",
    difficulty: "Normal",
    recommendedLevel: 15,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Incantation Table"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "VS Spell Buffs", icon: <GiClothes /> },
      { type: "Skill", name: "Lesser Tome of C", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "Man For Hire",
    date: "2020",
    location: "Brockenhurst",
    description: "You converse with a Wizard within the Mathematics Society casually. They mention an ancient scroll that they have been working on. The wizard claims that they've translated it into 'C#'. You enquire more. To understand the Wizards translation you secretly meet up with Windows Imperialists - the Linuxites best not see this...",
    questType: "Coding Story Line",
    difficulty: "Normal",
    recommendedLevel: 15,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Incantation Table"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "VS Spell Buffs", icon: <GiClothes /> },
      { type: "Skill", name: "Lesser Tome of C", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
  {
    title: "Archaic Incantation Table",
    date: "2020",
    location: "Brockenhurst",
    description: "You converse with a Wizard within the Mathematics Society casually. They mention an ancient scroll that they have been working on. The wizard claims that they've translated it into 'C#'. You enquire more. To understand the Wizards translation you secretly meet up with Windows Imperialists - the Linuxites best not see this...",
    questType: "Coding Story Line",
    difficulty: "Normal",
    recommendedLevel: 15,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Incantation Table"],
    progress: 100,
    animationFrames: meAnimation,
    rewards: [
      { type: "XP", name: "Experience", amount: 1000, icon: <FaStar /> },
      { type: "Item", name: "VS Spell Buffs", icon: <GiClothes /> },
      { type: "Skill", name: "Lesser Tome of C", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: meAnimation,
    specialItemRarity: "Rare",
  },
];