import {
  FaCode, FaStar, FaBrain, FaBookOpen,
  FaRaspberryPi,
  FaLaptopCode,
  FaBiohazard,
  FaBook,
  FaInfinity,
  FaProjectDiagram,
  FaBalanceScale,
  FaCogs
} from 'react-icons/fa';
import { PiBoxingGloveFill, PiLinuxLogoFill, PiCodeSimpleFill, PiGraphFill } from "react-icons/pi";
import type { JourneyStep, SpriteSheetData } from './JourneyTypes';
import { GiClothes, GiLaptop, GiSolarSystem, GiCrystalBall, GiScrollQuill, GiLaurels, GiGoldBar, GiAnvil } from 'react-icons/gi';
import { TbBrandVscode, TbMathSymbols, TbTopologyStar3 } from "react-icons/tb";
import { SiLetsencrypt, SiCplusplus, SiReact, SiTypescript } from "react-icons/si";
import { MdOutlineSportsKabaddi } from "react-icons/md";
import { TbOlympics } from "react-icons/tb";
import { FaDumbbell, FaPaintBrush } from 'react-icons/fa';
import { animations } from './animations';

export const journeySteps: JourneyStep[] = [
  {
    title: "The First Choice",
    date: "2015",
    location: "The Scholomance of Priestlands",
    description: "The journey begins! You stand at a crossroads. Will you join the Humanities cultists, weaving words and histories, or the STEM disciples, who seek to unravel the world's mechanics? This choice will shape your destiny.",
    questType: "The Scholar's Path",
    difficulty: "Trivial",
    recommendedLevel: 14,
    recommendedSkills: ["Curiosity", "Creativity", "Tome Inscription"],
    progress: 100,
    animationFrames: animations.schoolTeacher,
    rewards: [
      { name: "Experience", amount: 500, icon: <FaStar /> },
      { name: "Path of the STEM Disciple", icon: <GiSolarSystem /> },
      { name: "Lesser Python Spells", icon: <FaCode /> },
      { name: "Melee Training", icon: <PiBoxingGloveFill /> }
    ],
    specialItem: "GCSE Scroll",
    specialItemFrames: animations.gcseScroll,
    specialItemRarity: "Common",
  },
  {
    title: "Strings of Lightning",
    date: "2015",
    location: "The Port City of Southampton",
    description: "Not all magic comes from books and tomes. You pick up the electric guitar, channeling energy through strings of steel. Chords roar like thunder, solos crackle like lightning. A different discipline—music—joins your arsenal of skills.",
    questType: "Paths of Discovery",
    difficulty: "Normal",
    recommendedLevel: 16,
    recommendedSkills: ["Rhythm", "Creativity", "Persistence"],
    progress: 67,
    animationFrames: animations.musicMan,
    rewards: [
      { name: "Experience", amount: 1200, icon: <FaStar /> },
      { name: "Electric Guitar Riffs", icon: <FaBrain /> },
      { name: "Amplifier of Power", icon: <FaCogs /> },
    ],
    specialItem: "Guitar of Thunder",
    specialItemFrames: animations.guitar,
    specialItemRarity: "Epic",
  },

  {
    title: "Courts of Hardwood",
    date: "2016",
    location: "The Scholomance of Priestlands",
    description: "Between books and spells, you take to the court. Here, a smaller band of five face off, the rhythm of dribbling and the swish of nets forming their own kind of incantation. Victory depends not just on strength, but agility and teamwork.",
    questType: "The Way of the Warrior",
    difficulty: "Easy",
    recommendedLevel: 15,
    recommendedSkills: ["Agility Buff", "Quick Reflexes", "Team Spirit"],
    progress: 100,
    animationFrames: animations.bbMan,
    rewards: [
      { name: "Experience", amount: 600, icon: <FaStar /> },
      { name: "Basketball Medal", icon: <GiLaurels /> },
      { name: "Court Vision", icon: <FaBrain /> },
    ],
    specialItem: "Basketball Trophy",
    specialItemFrames: animations.bbTrophy,
    specialItemRarity: "Uncommon",
    prerequisites: ["The First Choice"],
  },
  {
    title: "Whispers of Open Source",
    date: "2017",
    location: "The Green Shires of Hampshire",
    description: "An unexpected encounter with a group called the Linuxites opens a new path. They reject the gilded cages of the Window Imperialists and MacOS Empire, speaking of freedom and control under a warlock named Linus. They promise to show you a better way.",
    questType: "The Arcane Arts",
    difficulty: "Easy",
    recommendedLevel: 15,
    recommendedSkills: ["CLI Curses", "Freedom Fighter Ideals", "Tome of Py"],
    progress: 100,
    animationFrames: animations.linuxite,
    rewards: [
      { name: "Experience", amount: 190, icon: <FaStar /> },
      { name: "Mastery of the Terminal", icon: <FaBookOpen /> },
      { name: "Arcane Pi Spells", icon: <FaRaspberryPi /> },
      { name: "Linux Loyalist", icon: <PiLinuxLogoFill /> },
    ],
    specialItem: "Raspberry Pi",
    specialItemFrames: animations.raspPi,
    specialItemRarity: "Uncommon",
    prerequisites: ["The First Choice"],
  },
    {
    title: "The Serpent in the Stacks",
    date: "2019",
    location: "The Port City of Southampton",
    description: "Deep within the library, the Linuxites speak of a serpent that guards ancient knowledge—a creature of pure logic that can weave incantations to manipulate reality. You must seek its wisdom to unlock new powers.",
    questType: "The Arcane Arts",
    difficulty: "Easy",
    recommendedLevel: 16,
    recommendedSkills: ["Common Incantation Table", "Member of Wizards Guild", "Linux Loyalty"],
    progress: 100,
    animationFrames: animations.snake,
    rewards: [
      { name: "Experience", amount: 380, icon: <FaStar /> },
      { name: "Interpreter Spells", icon: <FaBrain /> },
      { name: "Greater Python Mastery", icon: <FaLaptopCode /> },
    ],
    specialItem: "Tome of Py",
    specialItemFrames: animations.pyTome,
    specialItemRarity: "Common",
    prerequisites: ["Whispers of Open Source"],
  },
  {
    title: "The Assassin's Shadow",
    date: "2019",
    location: "The Forest College of Brockenhurst",
    description: "You learn of a dark underworld that creates spells to break other spells. They call themselves Dark Wizards. To defend against them, you must understand their ways, walking the line between the White and Dark arts without losing yourself.",
    questType: "The Arcane Arts",
    difficulty: "Hard",
    recommendedLevel: 16,
    recommendedSkills: ["Incantation Mastery", "Tome of Py", "Terminal Mastery", "Web Dimension Knowledge"],
    progress: 29,
    animationFrames: animations.wizardAssassin,
    rewards: [
      { name: "Experience", amount: 1000, icon: <FaStar /> },
      { name: "Cloak of Anonymity", icon: <GiClothes /> },
      { name: "Vulnerability Divination", icon: <GiCrystalBall /> },
    ],
    specialItem: "RSA Dagger",
    specialItemFrames: animations.RSADagger,
    specialItemRarity: "Epic",
    prerequisites: ["The Serpent in the Stacks"],
  },
  {
    title: "The Summons of the Society",
    date: "2020",
    location: "The Forest College of Brockenhurst",
    description: "The GCSE Scroll has unlocked new abilities. During celebrations, an ominous presence looms. 'Young scholar,' a voice intones, 'We are members of the Mathematics Society. We have been watching you. Join us outside.'",
    questType: "The Scholar's Path",
    difficulty: "Hard",
    recommendedLevel: 16,
    recommendedSkills: ["Strong STEM Curses", "Lesser Incantation Mastery", "Greater Tome Inscription"],
    progress: 100,
    animationFrames: animations.ALevelWizard,
    rewards: [
      { name: "Experience", amount: 1700, icon: <FaStar /> },
      { name: "Improved Fashion Sense", icon: <GiClothes /> },
      { name: "HP Incantation Table", icon: <GiLaptop /> },
      { name: "Incantation Buff", icon: <FaCode /> },
      { name: "Lesser Biology Spells", icon: <FaBiohazard /> },
    ],
    specialItem: "Advanced Spell Tome",
    specialItemFrames: animations.advancedSpellTome,
    specialItemRarity: "Uncommon",
    prerequisites: ["The First Choice"],
  },
  {
    title: "A Pact with the Imperialists",
    date: "2020",
    location: "The Forest College of Brockenhurst",
    description: "A wizard in the Society speaks of translating an ancient text into 'C#'. To understand this strange dialect, you must secretly meet the Windows Imperialists. The Linuxites must not discover this heresy.",
    questType: "The Arcane Arts",
    difficulty: "Normal",
    recommendedLevel: 17,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Diplomacy"],
    progress: 100,
    animationFrames: animations.imperialWizard,
    rewards: [
      { name: "Experience", amount: 1000, icon: <FaStar /> },
      { name: "Visual Studio Spell Buffs", icon: <TbBrandVscode /> },
      { name: "Lesser Tome of C#", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: animations.oopSpellBook,
    specialItemRarity: "Rare",
    prerequisites: ["The Serpent in the Stacks", "The Summons of the Society"],
  },
];