import {
  FaCode, FaStar, FaBrain, FaBookOpen,
  FaRaspberryPi,
  FaLaptopCode,
  FaBiohazard,
  FaBook,
  FaInfinity,
  FaProjectDiagram,
  FaBalanceScale,
  FaCogs
} from 'react-icons/fa';
import { PiBoxingGloveFill, PiLinuxLogoFill, PiCodeSimpleFill, PiGraphFill } from "react-icons/pi";
import type { JourneyStep, SpriteSheetData } from './JourneyTypes';
import { GiClothes, GiLaptop, GiSolarSystem, GiCrystalBall, GiScrollQuill, GiLaurels, GiGoldBar, GiAnvil } from 'react-icons/gi';
import { TbBrandVscode, TbMathSymbols, TbTopologyStar3 } from "react-icons/tb";
import { SiLetsencrypt, SiCplusplus, SiReact, SiTypescript } from "react-icons/si";
import { MdOutlineSportsKabaddi } from "react-icons/md";
import { TbOlympics } from "react-icons/tb";
import { FaDumbbell, FaPaintBrush } from 'react-icons/fa';
import { animations } from './animations';

export const journeySteps: JourneyStep[] = [
  {
    title: "The First Choice",
    date: "2015",
    location: "The Scholomance of Priestlands",
    description: "The journey begins! You stand at a crossroads. Will you join the Humanities cultists, weaving words and histories, or the STEM disciples, who seek to unravel the world's mechanics? This choice will shape your destiny.",
    questType: "The Scholar's Path",
    difficulty: "Trivial",
    recommendedLevel: 14,
    recommendedSkills: ["Curiosity", "Creativity", "Tome Inscription"],
    progress: 100,
    animationFrames: animations.schoolTeacher,
    rewards: [
      { name: "Experience", amount: 500, icon: <FaStar /> },
      { name: "Path of the STEM Disciple", icon: <GiSolarSystem /> },
      { name: "Lesser Python Spells", icon: <FaCode /> },
      { name: "Melee Training", icon: <PiBoxingGloveFill /> }
    ],
    specialItem: "GCSE Scroll",
    specialItemFrames: animations.gcseScroll,
    specialItemRarity: "Common",
  },
  {
    title: "Strings of Lightning",
    date: "2015",
    location: "The Port City of Southampton",
    description: "Not all magic comes from books and tomes. You pick up the electric guitar, channeling energy through strings of steel. Chords roar like thunder, solos crackle like lightning. A different discipline—music—joins your arsenal of skills.",
    questType: "Paths of Discovery",
    difficulty: "Normal",
    recommendedLevel: 16,
    recommendedSkills: ["Rhythm", "Creativity", "Persistence"],
    progress: 67,
    animationFrames: animations.musicMan,
    rewards: [
      { name: "Experience", amount: 1200, icon: <FaStar /> },
      { name: "Electric Guitar Riffs", icon: <FaBrain /> },
      { name: "Amplifier of Power", icon: <FaCogs /> },
    ],
    specialItem: "Guitar of Thunder",
    specialItemFrames: animations.guitar,
    specialItemRarity: "Epic",
  },

  {
    title: "Courts of Hardwood",
    date: "2016",
    location: "The Scholomance of Priestlands",
    description: "Between books and spells, you take to the court. Here, a smaller band of five face off, the rhythm of dribbling and the swish of nets forming their own kind of incantation. Victory depends not just on strength, but agility and teamwork.",
    questType: "The Way of the Warrior",
    difficulty: "Easy",
    recommendedLevel: 15,
    recommendedSkills: ["Agility Buff", "Quick Reflexes", "Team Spirit"],
    progress: 100,
    animationFrames: animations.basketballMan,
    rewards: [
      { name: "Experience", amount: 600, icon: <FaStar /> },
      { name: "Basketball Medal", icon: <GiLaurels /> },
      { name: "Court Vision", icon: <FaBrain /> },
    ],
    specialItem: "Basketball Trophy",
    specialItemFrames: animations.bbtrophy,
    specialItemRarity: "Uncommon",
    prerequisites: ["The First Choice"],
  },
  {
    title: "Whispers of Open Source",
    date: "2017",
    location: "The Green Shires of Hampshire",
    description: "An unexpected encounter with a group called the Linuxites opens a new path. They reject the gilded cages of the Window Imperialists and MacOS Empire, speaking of freedom and control under a warlock named Linus. They promise to show you a better way.",
    questType: "The Arcane Arts",
    difficulty: "Easy",
    recommendedLevel: 15,
    recommendedSkills: ["CLI Curses", "Freedom Fighter Ideals", "Tome of Py"],
    progress: 100,
    animationFrames: animations.linuxite,
    rewards: [
      { name: "Experience", amount: 190, icon: <FaStar /> },
      { name: "Mastery of the Terminal", icon: <FaBookOpen /> },
      { name: "Arcane Pi Spells", icon: <FaRaspberryPi /> },
      { name: "Linux Loyalist", icon: <PiLinuxLogoFill /> },
    ],
    specialItem: "Raspberry Pi",
    specialItemFrames: animations.pi,
    specialItemRarity: "Uncommon",
    prerequisites: ["The First Choice"],
  },
    {
    title: "The Serpent in the Stacks",
    date: "2019",
    location: "The Port City of Southampton",
    description: "Deep within the library, the Linuxites speak of a serpent that guards ancient knowledge—a creature of pure logic that can weave incantations to manipulate reality. You must seek its wisdom to unlock new powers.",
    questType: "The Arcane Arts",
    difficulty: "Easy",
    recommendedLevel: 16,
    recommendedSkills: ["Common Incantation Table", "Member of Wizards Guild", "Linux Loyalty"],
    progress: 100,
    animationFrames: animations.snake,
    rewards: [
      { name: "Experience", amount: 380, icon: <FaStar /> },
      { name: "Interpreter Spells", icon: <FaBrain /> },
      { name: "Greater Python Mastery", icon: <FaLaptopCode /> },
    ],
    specialItem: "Tome of Py",
    specialItemFrames: animations.pyTome,
    specialItemRarity: "Common",
    prerequisites: ["Whispers of Open Source"],
  },
  {
    title: "The Assassin's Shadow",
    date: "2019",
    location: "The Forest College of Brockenhurst",
    description: "You learn of a dark underworld that creates spells to break other spells. They call themselves Dark Wizards. To defend against them, you must understand their ways, walking the line between the White and Dark arts without losing yourself.",
    questType: "The Arcane Arts",
    difficulty: "Hard",
    recommendedLevel: 16,
    recommendedSkills: ["Incantation Mastery", "Tome of Py", "Terminal Mastery", "Web Dimension Knowledge"],
    progress: 29,
    animationFrames: animations.wizardAssassin,
    rewards: [
      { name: "Experience", amount: 1000, icon: <FaStar /> },
      { name: "Cloak of Anonymity", icon: <GiClothes /> },
      { name: "Vulnerability Divination", icon: <GiCrystalBall /> },
    ],
    specialItem: "RSA Dagger",
    specialItemFrames: animations.RSADagger,
    specialItemRarity: "Epic",
    prerequisites: ["The Serpent in the Stacks"],
  },
  {
    title: "The Summons of the Society",
    date: "2020",
    location: "The Forest College of Brockenhurst",
    description: "The GCSE Scroll has unlocked new abilities. During celebrations, an ominous presence looms. 'Young scholar,' a voice intones, 'We are members of the Mathematics Society. We have been watching you. Join us outside.'",
    questType: "The Scholar's Path",
    difficulty: "Hard",
    recommendedLevel: 16,
    recommendedSkills: ["Strong STEM Curses", "Lesser Incantation Mastery", "Greater Tome Inscription"],
    progress: 100,
    animationFrames: animations.ALevelWizard,
    rewards: [
      { name: "Experience", amount: 1700, icon: <FaStar /> },
      { name: "Improved Fashion Sense", icon: <GiClothes /> },
      { name: "HP Incantation Table", icon: <GiLaptop /> },
      { name: "Incantation Buff", icon: <FaCode /> },
      { name: "Lesser Biology Spells", icon: <FaBiohazard /> },
    ],
    specialItem: "Advanced Spell Tome",
    specialItemFrames: animations.advancedSpellTome,
    specialItemRarity: "Uncommon",
    prerequisites: ["The First Choice"],
  },
  {
    title: "A Pact with the Imperialists",
    date: "2020",
    location: "The Forest College of Brockenhurst",
    description: "A wizard in the Society speaks of translating an ancient text into 'C#'. To understand this strange dialect, you must secretly meet the Windows Imperialists. The Linuxites must not discover this heresy.",
    questType: "The Arcane Arts",
    difficulty: "Normal",
    recommendedLevel: 17,
    recommendedSkills: ["Good Incantation Mastery", "Tome of Py", "Diplomacy"],
    progress: 100,
    animationFrames: animations.imperialWizard,
    rewards: [
      { name: "Experience", amount: 1000, icon: <FaStar /> },
      { name: "Visual Studio Spell Buffs", icon: <TbBrandVscode /> },
      { name: "Lesser Tome of C#", icon: <FaBook /> },
    ],
    specialItem: "OOP Spellbook",
    specialItemFrames: animations.oopSpellBook,
    specialItemRarity: "Rare",
    prerequisites: ["The Serpent in the Stacks", "The Summons of the Society"],
  },
    {
    title: "The Champion's Bout",
    date: "2020",
    location: "The Arenas of London",
    description: "Lost in tomes and incantations, you realize your melee skills have dulled. You return to the art of hand-to-hand combat, rising through the leagues until you find yourself at the national championship. It is time to test your body as well as your mind.",
    questType: "The Way of the Warrior",
    difficulty: "Heroic",
    recommendedLevel: 18,
    recommendedSkills: ["High Stamina", "Strength Buff", "Combat Intelligence"],
    progress: 100,
    animationFrames: animations.fighter,
    rewards: [
      { name: "Experience", amount: 1000, icon: <FaStar /> },
      { name: "Fighter's Medallion", icon: <GiLaurels /> },
      { name: "Combat Focus", icon: <FaBrain /> },
    ],
    specialItem: "Respect Buff",
    specialItemFrames: animations.respectBuff,
    specialItemRarity: "Epic",
    prerequisites: ["Courts of Hardwood"],
  },
  {
    title: "A Pilgrimage to the North",
    date: "2022",
    location: "The Northern Citadel of Heriot-Watt",
    description: "With the Advanced Spell Tome in hand, you journey north. Rumours say a powerful branch of the Mathematics Society lies in refuge there. You set out, anxious but determined to deepen your understanding of the world's fundamental laws.",
    questType: "The Scholar's Path",
    difficulty: "Normal",
    recommendedLevel: 18,
    recommendedSkills: ["Advanced Spell Casting", "Meet Mathematicians", "Greater Tome Inscription"],
    progress: 100,
    animationFrames: animations.theNorth,
    rewards: [
      { name: "Experience", amount: 1200, icon: <FaStar /> },
      { name: "Secrets Spell Casting", icon: <SiLetsencrypt /> },
      { name: "Advanced Maths Casting", icon: <FaBook /> },
      { name: "Advanced Athletic Abilities", icon: <MdOutlineSportsKabaddi /> },
      { name: "Befriended Grand Wizard", icon: <FaBook /> },
    ],
    specialItem: "The Mathematician's Manifesto",
    specialItemFrames: animations.mathManefesto,
    specialItemRarity: "Epic",
    prerequisites: ["The Summons of the Society"],
  },
    {
    title: "The Forge of the JVM",
    date: "2022",
    location: "The Northern Citadel of Heriot-Watt",
    description: "Whispers spread of an enchanted forge known as the Java Virtual Machine. Unlike Python's fluid incantations, this magic is structured, strict, and resilient. To wield it is to command a language that powers vast kingdoms of code.",
    questType: "The Arcane Arts",
    difficulty: "Normal",
    recommendedLevel: 20,
    recommendedSkills: ["OOP Spellbook", "Incantation Discipline", "Patience"],
    progress: 70,
    animationFrames: animations.JVMGolem,
    rewards: [
      { name: "Experience", amount: 1800, icon: <FaStar /> },
      { name: "Java Mastery", icon: <FaBookOpen /> },
      { name: "Strong Type Binding", icon: <FaCogs /> },
    ],
    specialItem: "Tome of the JVM",
    specialItemFrames: animations.JVMTome,
    specialItemRarity: "Rare",
    prerequisites: ["A Pilgrimage to the North", "A Pact with the Imperialists"],
  },
  {
    title: "The Uncrowned King",
    date: "2022",
    location: "The Arenas of London",
    description: "You return to the championship—stronger, faster, smarter. You fight with the precision of a mathematician and the spirit of a warrior. Though victory is claimed by another, your skill earns you a legendary status among your peers.",
    questType: "The Way of the Warrior",
    difficulty: "Deadly",
    recommendedLevel: 19,
    recommendedSkills: ["High Stamina", "Strength Buff", "BCCMA Respect", "Veteran's Experience"],
    progress: 100,
    animationFrames: animations.fightKing,
    rewards: [
      { name: "Experience", amount: 5000, icon: <FaStar /> },
      { name: "Championship Gloves", icon: <PiBoxingGloveFill /> },
      { name: "Unbreakable Will", icon: <FaBrain /> },
    ],
    specialItem: "Silver Medal of the Uncrowned",
    specialItemFrames: animations.silverMedal,
    specialItemRarity: "Epic",
    prerequisites: ["The Champion's Bout"],
  },
  {
    title: "A Fool's Gamble",
    date: "2022",
    location: "The Londoninium Sprawl",
    description: "Drawn by tales of quick riches, you enter the chaotic realm of financial trading. It's a dangerous game of predicting the unpredictable, where fortunes are won and lost in moments. You try to read the market's cryptic signs, hoping not to lose your shirt.",
    questType: "The Gold-Spinner's Gambit",
    difficulty: "Normal",
    recommendedLevel: 19,
    recommendedSkills: ["Risk Assessment", "Emotional Detachment", "Basic Economics"],
    progress: 100,
    animationFrames: animations.richMan,
    rewards: [
      { name: "Experience", amount: 800, icon: <FaStar /> },
      { name: "Slightly Emptier Coin Purse", icon: <GiGoldBar /> },
      { name: "Humility", icon: <FaBrain /> },
    ],
    specialItem: "A Valuable Lesson",
    specialItemFrames: animations.emptyCoin,
    specialItemRarity: "Common",
    prerequisites: ["A Pilgrimage to the North"],
  },
    {
    title: "The Clash of the Fifteen",
    date: "2022",
    location: "The Grand Athenaeum of Queen Mary",
    description: "Your mind sharpens in lecture halls, but the pitch calls you to battle. You take up the sport of Rugby, where fifteen warriors clash in contests of speed, strength, and strategy. Each match is a proving ground for resilience and camaraderie.",
    questType: "The Way of the Warrior",
    difficulty: "Heroic",
    recommendedLevel: 18,
    recommendedSkills: ["Strength Buff", "Team Coordination", "Fearless Spirit"],
    progress: 100,
    animationFrames: animations.rugby,
    rewards: [
      { name: "Experience", amount: 2200, icon: <FaStar /> },
      { name: "University Jersey", icon: <GiLaurels /> },
      { name: "Tactical Awareness", icon: <FaBrain /> },
    ],
    specialItem: "Rugby Ball of Unity",
    specialItemFrames: animations.rugbyBall,
    specialItemRarity: "Epic",
    prerequisites: ["A Pilgrimage to the North"],
  },
  {
    title: "The Serpent's Coils",
    date: "2025",
    location: "The London Grappling Pits",
    description: "A new discipline calls from the warrior's path. Not of striking, but of grappling. You begin training in the 'Gentle Art' of Brazilian Jiu-Jitsu, a deadly dance where leverage and technique form suffocating coils to subdue any opponent, no matter their size.",
    questType: "The Way of the Warrior",
    difficulty: "Normal",
    recommendedLevel: 21,
    recommendedSkills: ["Flexibility", "Problem Solving", "Humility"],
    progress: 5,
    animationFrames: meAnimation,
    rewards: [
      { name: "Experience", amount: 3000, icon: <FaStar /> },
      { name: "Submission Holds", icon: <MdOutlineSportsKabaddi /> },
      { name: "Guard Mastery", icon: <FaCogs /> },
    ],
    specialItem: "White Belt of Humility",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
    prerequisites: ["The Herculean Trial"],
  },
  {
    title: "The Takedown Trial",
    date: "2025",
    location: "The London Grappling Pits",
    description: "To complement the ground-based serpent's art, you seek mastery over the standing clash. Wrestling teaches the explosive power to control an opponent's center of gravity, to dominate the clinch, and to dictate where the battle is fought. This is the art of the takedown.",
    questType: "The Way of the Warrior",
    difficulty: "Normal",
    recommendedLevel: 21,
    recommendedSkills: ["Explosive Power", "Balance", "Grit"],
    progress: 5,
    animationFrames: meAnimation,
    rewards: [
      { name: "Experience", amount: 3000, icon: <FaStar /> },
      { name: "Takedown Offense", icon: <TbOlympics /> },
      { name: "Positional Control", icon: <FaProjectDiagram /> },
    ],
    specialItem: "Wrestler's Cauliflower Charm",
    specialItemFrames: meAnimation,
    specialItemRarity: "Common",
    prerequisites: ["The Herculean Trial"],
  },
];